OA_KEY = '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'
OA_ORGANIZATION = None
# OA_KEY = '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'
# OA_ORGANIZATION = 'org-hdSY2NVrYa06AwGU4XaZHmZ2'
